# Generated by Django 5.1.7 on 2025-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
