# Generated by Django 5.1.7 on 2025-06-19 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionRiskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=10, unique=True)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('severe_cases', models.PositiveIntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('most_common_crime', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Region Risk Summaries',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('national_id', models.CharField(max_length=16, unique=True)),
                ('known_addresses', models.TextField()),
                ('criminal_record_summary', models.TextField()),
                ('biometric_data', models.JSONField(blank=True, null=True)),
                ('behavior_patterns', models.JSONField(blank=True, null=True)),
                ('predicted_risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prediction_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_prediction_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['predicted_risk_level'], name='suspect_sus_predict_05a2f7_idx'), models.Index(fields=['national_id'], name='suspect_sus_nationa_0d8650_idx'), models.Index(fields=['last_prediction_date'], name='suspect_sus_last_pr_c02b29_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrimeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('burglary', 'Burglary'), ('fraud', 'Fraud'), ('drug_offense', 'Drug Offense'), ('vandalism', 'Vandalism'), ('robbery', 'Robbery'), ('domestic_violence', 'Domestic Violence'), ('cybercrime', 'Cybercrime'), ('other', 'Other')], max_length=50)),
                ('location_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('public', 'Public Space'), ('educational', 'Educational'), ('transport', 'Transportation'), ('other', 'Other')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('is_severe', models.BooleanField(default=False)),
                ('severity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prediction_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspects', models.ManyToManyField(blank=True, related_name='incidents', to='suspect.suspect')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crime_type'], name='suspect_cri_crime_t_b04255_idx'), models.Index(fields=['region_code'], name='suspect_cri_region__d0b119_idx'), models.Index(fields=['is_severe'], name='suspect_cri_is_seve_d73a74_idx'), models.Index(fields=['created_at'], name='suspect_cri_created_9616c1_idx')],
            },
        ),
    ]
