# Generated by Django 5.1.7 on 2025-06-19 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_incident_predicted_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('closed', 'Closed')], max_length=20)),
                ('priority', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_officers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('related_incidents', models.ManyToManyField(blank=True, related_name='cases', to='incidents.incident')),
            ],
        ),
    ]
