# Generated by Django 5.1.7 on 2025-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_number',
        ),
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.CharField(default='temp_case', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
