# Generated by Django 5.1.7 on 2025-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_remove_case_case_number_case_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
