# Generated by Django 5.1.7 on 2025-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(default='NULL', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
