# Generated by Django 5.1.7 on 2025-06-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_case_case_id'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='related_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='case.case'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
