# Generated by Django 5.1.7 on 2025-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('encoded_crime_type', models.IntegerField()),
                ('predicted_severity', models.CharField(choices=[('Severe', 'Severe'), ('Not Severe', 'Not Severe')], max_length=20)),
                ('prediction_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crime_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crime_type'], name='crime_predi_crime_t_72851f_idx'), models.Index(fields=['predicted_severity'], name='crime_predi_predict_f55a76_idx'), models.Index(fields=['created_at'], name='crime_predi_created_16dcb4_idx')],
            },
        ),
    ]
