# Generated by Django 5.1.7 on 2025-06-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='predicted_severity',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
